language: python
python:
  - 3.4
install:
  - pip install -q -M -r requirements/development.txt
before_script:
  - echo '{"ADMINS":[["",""]],"SECRET_KEY":"12345678901234567890123456789012345678901234567890"}' | cat > galtrace/settings/secret.json
script:
  - python manage.py gt_test --settings=galtrace.settings.development
